{-# LANGUAGE TemplateHaskell #-}

module Entities.Variable(Variable(..)) where

import Data.Aeson.TH
import Entities.Type

data Variable = Variable
  { id :: Int
  , variableType :: Type
  , name :: String
  , autoGeneratedId :: Int
  , referenceCount :: Int
  , active :: Bool
  } deriving (Eq, Show)

$(deriveJSON defaultOptions ''Variable)
